on:
  push:
    branches:
      - upstream

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Update Contributors in README
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Update Contributors List in README
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
