name: Fetch new changes from upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '43 4 * * *'

concurrency:
  group: fetch

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.email "automation@github.com"
          git config --global user.name "fetch_upstream.yml"

      - name: Fetch and Rebase from Upstream
        run: |
          git remote add upstream https://github.com/bluesky-social/social-app.git
          git fetch upstream main
          git checkout --track origin/main
          git rebase upstream/main

      - name: Push Changes
        run: git push -f origin HEAD
